Repository SWM-WeLike2Coding/ELSwhere-mobile, pull requests merged in 2024-11, with the labels that each got.

#317 feat: 상품들에 대해 AI 분석 결과 보여주기 기능 추가
  assets/data/ai_result.txt
  assets/data/mcs_result.txt
  lib/config/config.dart
  lib/config/strings.dart
  lib/ui/screens/other/splash_screen.dart
  lib/ui/views/product/els_product_detail_view.dart
  lib/ui/widgets/analysis_result_graph.dart
  pubspec.yaml
Labels: enhancement, feat

#321 feat: AI 및 분석 결과 핸드폰 방향에 따라 레이아웃 위치 수정
  ios/Runner.xcodeproj/xcshareddata/xcschemes/prod.xcscheme
  lib/ui/views/product/els_product_detail_view.dart
  lib/ui/widgets/analysis_result_graph.dart
Labels: enhancement, fix, design

#323 hotfix: 버전 업데이트 비교 로직 오류 수정
  android/app/google-services.json
  ios/Runner/GoogleService-Info.plist
  lib/ui/screens/other/splash_screen.dart
Labels: bug, hotfix

#328 fix: 설문조사 페이지 버그 수정
  lib/ui/screens/home/investment_propensity_screen.dart
Labels: fix, design

#329 fix: 닉네임 수정 페이지로 가는 클릭 영역 확장
  lib/ui/screens/more/more_screen.dart
Labels: enhancement, fix

#330 fix: 캘린더 디자인 보완
  lib/ui/screens/home/attention_subscription_schedule_screen.dart
Labels: enhancement, fix

#334 feat: 설문조사 페이지 api 연동
  ios/Runner/GoogleService-Info.plist
  lib/data/models/dtos/user/response_investment_type_dto.dart
  lib/data/models/dtos/user/response_investment_type_dto.g.dart
  lib/data/providers/user_info_provider.dart
  lib/data/services/user/user_service.g.dart
  lib/ui/screens/home/investment_propensity_screen.dart
Labels: enhancement, feat

#335 fix: 상품 비교 관련 로직 오류 수정
  lib/config/config.dart
  lib/config/strings.dart
  lib/data/providers/els_product_provider.dart
  lib/data/providers/waiting_provider.dart
  lib/main.dart
  lib/ui/screens/home/holding_products_screen.dart
  lib/ui/screens/other/initial_screen.dart
  lib/ui/screens/other/main_screen.dart
  lib/ui/screens/other/splash_screen.dart
  lib/ui/screens/other/waiting_screen.dart
  lib/ui/screens/product/els_product_detail_screen.dart
  lib/ui/screens/product/product_screen.dart
  lib/ui/views/product/els_product_list_view.dart
  lib/ui/widgets/els_product_card.dart
Labels: bug, fix

#341 상품 비교 관련 추가 및 수정사항
  lib/ui/screens/product/compare_product_screen.dart
  lib/ui/screens/product/product_screen.dart
Labels: enhancement, feat, fix, hotfix

#344 fix: 상품 마감일 계산방법 수정
  lib/data/providers/els_products_provider.dart
  lib/data/providers/ticker_symbol_provider.dart
  lib/data/services/other/yfinance_service.dart
  lib/ui/screens/home/attention_subscription_schedule_screen.dart
  lib/ui/screens/home/home_screen.dart
  lib/ui/screens/product/compare_product_screen.dart
  lib/ui/views/product/els_product_detail_view.dart
  lib/ui/widgets/els_product_card.dart
  lib/ui/widgets/holding_product_card.dart
  lib/ui/widgets/hot_product_card.dart
  lib/ui/widgets/stock_price_graph.dart
  lib/utils/utils.dart
Labels: fix, hotfix

#346 feat: 보유 상품 화면에 상품 추가 버튼 추가
  lib/ui/screens/home/holding_products_screen.dart
  lib/ui/widgets/custom_appbar.dart
Labels: enhancement, feat

#350 fix: 주가 지수 그래프에서 상장 시기가 다른 경우 데이터 보정
  lib/ui/widgets/stock_price_graph.dart
Labels: bug, fix, hotfix

#349 설문 데이터 기반 product_screen에 투자 성향 기반 상품 보여주기 기능 개발
  ios/Runner.xcodeproj/project.pbxproj
  lib/data/models/dtos/user/els_product_for_schedule_dto.dart
  lib/data/models/dtos/user/els_product_for_schedule_dto.g.dart
  lib/data/providers/user_info_provider.dart
  lib/data/services/user/user_service.dart
  lib/data/services/user/user_service.g.dart
  lib/ui/screens/home/attention_subscription_schedule_screen.dart
  lib/ui/screens/home/home_screen.dart
  lib/ui/screens/home/investment_propensity_screen.dart
  lib/ui/screens/home/personalized_products_screen.dart
  lib/ui/screens/other/initial_screen.dart
  lib/ui/screens/product/product_screen.dart
  lib/ui/views/home/hot_products_list_view.dart
  lib/ui/views/home/interesting_product_list_view.dart
  lib/ui/views/home/personalized_products_list_view.dart
  lib/ui/views/product/els_product_list_view.dart
  lib/ui/widgets/els_product_card.dart
Labels: feat, design

#353 fix: 상품 비교 상세화면에서 상품 중복으로 표시되는 오류 수정
  lib/data/providers/els_product_provider.dart
Labels: bug, fix, hotfix

#355 fix: 상품 상세 화면으로 들어갈 때, 다른 상품이 불러져 오는 오류 수정
  lib/data/providers/els_product_provider.dart
  lib/ui/screens/product/compare_product_screen.dart
  lib/ui/screens/product/els_product_detail_screen.dart
  lib/ui/widgets/els_product_card.dart
  lib/ui/widgets/holding_product_card.dart
  lib/ui/widgets/hot_product_card.dart
Labels: bug, fix, hotfix

#358 hotfix: 회원가입 헤더 제거, 앱 정보 오표기 수정
  lib/data/services/user/user_service.dart
  lib/data/services/user/user_service.g.dart
  lib/ui/screens/more/more_screen.dart
Labels: bug, fix

#359 fix: 투자 경험 없다고 입력 시 투자 가이드로 이동 및 버그 수정
  lib/data/providers/user_info_provider.dart
  lib/ui/screens/home/investment_propensity_screen.dart
  lib/ui/screens/other/initial_screen.dart
Labels: bug, feat, fix

#361 feat: AI 추천 상품 페이지 및 메인 화면 진입점 개발
  assets/animations/animation_ai.json
  lib/config/app_resource.dart
  lib/config/strings.dart
  lib/data/models/dtos/product/response_product_comparison_target_dto.dart
  lib/data/models/dtos/user/els_product_for_schedule_dto.g.dart
  lib/data/providers/analysis/ai_product_provider.dart
  lib/data/providers/post/post_provider.dart
  lib/data/providers/product/els_product_provider.dart
  lib/data/providers/product/els_products_provider.dart
  lib/data/providers/product/hot_products_provider.dart
  lib/data/providers/token_provider.dart
  lib/data/providers/user/user_info_provider.dart
  lib/data/services/product/els_product_service.dart
  lib/data/services/product/els_product_service.g.dart
  lib/data/services/user/user_service.g.dart
  lib/main.dart
  lib/ui/screens/home/ai_recommendation_product_screen.dart
  lib/ui/screens/home/attention_subscription_schedule_screen.dart
  lib/ui/screens/home/holding_products_screen.dart
  lib/ui/screens/home/home_screen.dart
  lib/ui/screens/home/investment_propensity_screen.dart
  lib/ui/screens/home/personalized_products_screen.dart
  lib/ui/screens/home/redemption_schedule_screen.dart
  lib/ui/screens/home/subscription_end_schedule_screen.dart
  lib/ui/screens/more/change_nickname_screen.dart
  lib/ui/screens/more/member_quit_screen.dart
  lib/ui/screens/more/more_screen.dart
  lib/ui/screens/more/notice_detail_screen.dart
  lib/ui/screens/other/home_screen.dart
  lib/ui/screens/other/initial_screen.dart
  lib/ui/screens/other/login_screen.dart
  lib/ui/screens/other/splash_screen.dart
  lib/ui/screens/other/terms_and_conditions_consent_screen.dart
  lib/ui/screens/product/compare_product_screen.dart
  lib/ui/screens/product/els_product_detail_screen.dart
  lib/ui/screens/product/product_screen.dart
  lib/ui/screens/product/search_product_screen.dart
  lib/ui/views/home/ai_recommendation_products_list_view.dart
  lib/ui/views/home/holding_products_list_view.dart
  lib/ui/views/home/hot_products_list_view.dart
  lib/ui/views/home/interesting_product_list_view.dart
  lib/ui/views/home/personalized_products_list_view.dart
  lib/ui/views/more/notice_list_view.dart
  lib/ui/views/product/add_holding_product_modal.dart
  lib/ui/views/product/detail_search_modal.dart
  lib/ui/views/product/els_product_detail_view.dart
  lib/ui/views/product/els_product_list_view.dart
  lib/ui/views/product/my_investment_status_view.dart
  lib/ui/widgets/ai_recommendation_product_card.dart
  lib/ui/widgets/els_product_card.dart
  lib/ui/widgets/holding_product_card.dart
  lib/ui/widgets/hot_product_card.dart
  lib/ui/widgets/notice_item.dart
  lib/ui/widgets/price_ratio_table.dart
  lib/ui/widgets/stock_price_graph.dart
  pubspec.yaml
Labels: enhancement, feat

#363 hotfix: AI 상품 화면 진입 후 다른 페이지 들어갈 시 로딩 완료가 먼저 표시되는 오류 수정
  lib/ui/screens/home/ai_recommendation_product_screen.dart
  lib/ui/screens/product/els_product_detail_screen.dart
Labels: bug, fix, hotfix

#365 Hotfix/analysis graph
  lib/ui/widgets/analysis_result_graph.dart
  pubspec.yaml
Labels: bug, hotfix

#367 hotfix: late final 변수가 한번 더 초기화되어 오류가 나는 현상 수정
  lib/ui/screens/product/compare_product_screen.dart
Labels: bug, hotfix
