Repository SWM-WeLike2Coding/ELSwhere-mobile, pull requests merged in 2024-10, with the labels that each got.

#254 feat: 상품 상세 페이지에서 좋아요 개수 표기
  lib/config/app_resource.dart
  lib/data/models/dtos/response_single_product_dto.dart
  lib/data/models/dtos/response_single_product_dto.g.dart
  lib/data/providers/els_product_provider.dart
  lib/ui/screens/announcement_screen.dart
  lib/ui/screens/attention_products_screen.dart
  lib/ui/screens/attention_setting_screen.dart
  lib/ui/screens/attention_subscription_schedule_screen.dart
  lib/ui/screens/change_nickname_screen.dart
  lib/ui/screens/compare_product_screen.dart
  lib/ui/screens/els_product_detail_screen.dart
  lib/ui/screens/holding_products_screen.dart
  lib/ui/screens/home_screen.dart
  lib/ui/screens/investment_guide_detail_screen.dart
  lib/ui/screens/investment_guide_screen.dart
  lib/ui/screens/investment_propensity_screen.dart
  lib/ui/screens/member_quit_screen.dart
  lib/ui/screens/notification_screen.dart
  lib/ui/screens/redemption_schedule_screen.dart
  lib/ui/screens/service_agreement_screen.dart
  lib/ui/screens/subscription_end_schedule_screen.dart
  lib/ui/views/alarm_setting_modal.dart
  lib/ui/views/detail_search_modal.dart
  lib/ui/views/els_product_detail_view.dart
  lib/ui/views/holding_products_list_view.dart
  lib/ui/widgets/els_product_card.dart
  lib/ui/widgets/holding_product_card.dart
  lib/ui/widgets/hot_product_card.dart
  lib/ui/widgets/search_text_field.dart
  pubspec.yaml
Labels: enhancement, feat

#258 feat: 상품 회차 번호로 검색 기능 추가
  lib/data/providers/els_products_provider.dart
  lib/data/services/els_product_service.dart
  lib/data/services/els_product_service.g.dart
  lib/ui/screens/search_product_screen.dart
  lib/ui/views/detail_search_modal.dart
  lib/ui/widgets/search_text_field.dart
Labels: enhancement, feat, fix

#264 fix: 앱 빌드 버전 불일치로 배포가 안되는 현상 수정
  android/app/build.gradle
  lib/config/app_resource.dart
  lib/main.dart
  lib/ui/screens/announcement_screen.dart
  lib/ui/screens/attention_products_screen.dart
  lib/ui/screens/attention_subscription_schedule_screen.dart
  lib/ui/screens/change_nickname_screen.dart
  lib/ui/screens/home_screen.dart
  lib/ui/screens/investment_guide_detail_screen.dart
  lib/ui/screens/investment_guide_screen.dart
  lib/ui/screens/investment_propensity_screen.dart
  lib/ui/screens/login_screen.dart
  lib/ui/screens/member_quit_screen.dart
  lib/ui/screens/more_screen.dart
  lib/ui/screens/product_screen.dart
  lib/ui/screens/redemption_schedule_screen.dart
  lib/ui/screens/search_product_screen.dart
  lib/ui/screens/service_agreement_screen.dart
  lib/ui/screens/subscription_end_schedule_screen.dart
  lib/ui/views/alarm_setting_modal.dart
  lib/ui/views/detail_search_modal.dart
  lib/ui/views/holding_products_list_view.dart
  lib/ui/widgets/els_product_card.dart
  lib/ui/widgets/holding_product_card.dart
  lib/ui/widgets/stock_index_list.dart
  pubspec.yaml
Labels: fix, hotfix

#266 fix: 안드로이드 keystore 관련 gradle 업데이트
  android/app/build.gradle
  pubspec.yaml
Labels: fix, hotfix

#268 feat: 상품 리스트에서 좋아요한 상품들 하트 모양으로 확인 가능하도록 기능 추가
  lib/data/models/dtos/user_like_product_dto.dart
  lib/data/models/dtos/user_like_product_dto.g.dart
  lib/data/providers/els_product_provider.dart
  lib/data/services/user_service.dart
  lib/data/services/user_service.g.dart
  lib/ui/widgets/els_product_card.dart
  lib/ui/widgets/hot_product_card.dart
Labels: enhancement, feat, design

#274 feat: 앱 업데이트 문구 표시 기능 추가
  lib/config/app_resource.dart
  lib/config/config.dart
  lib/main.dart
  lib/ui/screens/splash_screen.dart
  pubspec.yaml
Labels: enhancement, feat

#278 fix: iOS 상품 회차 번호 검색 시 완료 버튼이 없어서 검색 안되는 문제 해결
  lib/ui/screens/product/search_product_screen.dart
Labels: bug, fix, hotfix

#286 feat: 주가지수 기간 5년 추가
  lib/data/services/other/yfinance_service.dart
  lib/ui/views/product/stock_price_graph_view.dart
  lib/ui/widgets/stock_price_graph.dart
Labels: enhancement, fix

#289 hotfix: FirebaseMessaging fetch 오류 수정
  lib/data/providers/user_info_provider.dart
  lib/main.dart
Labels: bug, fix, hotfix

#297 feat: 상품들에 대해 AI 분석 결과(위험도) 표시 기능 추가
  .github/pull_request_template.md
  lib/config/app_resource.dart
  lib/config/strings.dart
  lib/data/models/dtos/product/response_product_comparison_target_dto.dart
  lib/data/models/dtos/product/response_product_comparison_target_dto.g.dart
  lib/data/models/dtos/product/response_single_product_dto.dart
  lib/data/models/dtos/product/response_single_product_dto.g.dart
  lib/data/models/dtos/product/summarized_product_dto.dart
  lib/data/models/dtos/product/summarized_product_dto.g.dart
  lib/ui/screens/product/product_screen.dart
  lib/ui/views/product/els_product_detail_view.dart
  lib/ui/widgets/danger_degree_box.dart
  lib/ui/widgets/els_product_card.dart
  lib/utils/ai_result_converter.dart
  lib/utils/utils.dart
Labels: enhancement, feat, design

#299 fix: 상품 검색 관련 일부 텍스트 수정
  lib/config/strings.dart
  lib/ui/screens/product/product_screen.dart
  lib/ui/views/product/detail_search_modal.dart
  lib/ui/widgets/search_text_field.dart
Labels: fix

#308 fix: 보유 상품에서 상품 삭제시 null value 오류 수정
  .gitignore
  ios/Runner/GoogleService-Info.plist
  lib/config/strings.dart
  lib/ui/screens/home/holding_products_screen.dart
  lib/ui/views/product/els_product_detail_view.dart
  lib/ui/widgets/custom_appbar.dart
Labels: bug, fix, hotfix

#311 fix: 현재 청약 중인 상품 & HOT 상품에 상품 위험도를 보여주도록 수정
  lib/ui/views/product/els_product_detail_view.dart
  lib/ui/widgets/els_product_card.dart
  lib/ui/widgets/hot_product_card.dart
Labels: enhancement, fix

#313 fix: 관심 상품 화면에서 상품 삭제시 증권사 아이콘 밀리는 현상 수정
  lib/data/models/dtos/product/response_product_comparison_target_dto.g.dart
  lib/data/models/dtos/product/response_single_product_dto.g.dart
  lib/data/models/dtos/product/summarized_product_dto.g.dart
  lib/data/models/dtos/user/response_interesting_product_dto.dart
  lib/data/models/dtos/user/response_interesting_product_dto.g.dart
  lib/data/providers/els_products_provider.dart
  lib/ui/views/home/interesting_product_list_view.dart
Labels: bug, fix, hotfix
